#!/usr/bin/env bun

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const CURRENT_DIR = dirname(fileURLToPath(import.meta.url));
const TARGET_FILE = resolve(CURRENT_DIR, '../src/generated/telemetry-config.ts');

const telemetryConfig = {
  azureMonitorKey: process.env.TENSORFLEET_AZURE_MONITOR_KEY ?? '',
  sentryDsn: process.env.TENSORFLEET_SENTRY_DSN ?? '',
  sentryEnvironment: process.env.TENSORFLEET_RUNTIME_ENV ?? process.env.NODE_ENV ?? 'development'
};

const fileBanner = '// Auto-generated by scripts/write-telemetry-config.ts. DO NOT EDIT MANUALLY.\n';
const fileBody = `export const TELEMETRY_CONFIG = ${JSON.stringify(telemetryConfig, null, 2)} as const;\n`;
const fileContents = `${fileBanner}${fileBody}`;

if (existsSync(TARGET_FILE)) {
  const current = readFileSync(TARGET_FILE, 'utf8');
  if (current === fileContents) {
    console.log(`Telemetry config already up to date at ${TARGET_FILE}`);
    process.exit(0);
  }
}

mkdirSync(dirname(TARGET_FILE), { recursive: true });
writeFileSync(TARGET_FILE, fileContents);
console.log(`Telemetry config written to ${TARGET_FILE}`);
